### ISSUE TITLE
Issue with transaction ID uniqueness

### ISSUE THREAD

**Issue by mlaitinen** [eino-makitalo/account_bank_statement_import_oko#1]
So it turns out there can be bank statement lines with identical archival id AND date. This just happened to us.

My solution for this was to append a incremental value `index`: https://github.com/avoinsystems/account_bank_statement_import_op/commit/08cc3518d9b1ff18a02a72767306988ae7e5a8ed

**Comment by eino-makitalo** [comment]
Indeed, we discussed that OP is using same archival ID if it's repeatable payment

**Comment by mlaitinen** [comment]
Yep, but this wasn't a repeatable payment AFAIK. There were two identical lines for the same date and the only difference was the sum. No payment reference either, just "Viitesiirto".
